/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  create_counter: {};
} | {
  update_counter: {
    action_type: ActionType;
    value: Uint128;
  };
} | {
  set_counter: {
    value: Uint128;
  };
};
export type ActionType = "add" | "sub" | "mul";
export type Uint128 = string;
export type QueryMsg = {
  query_counters: {
    addresses?: string[] | null;
  };
} | {
  query_total_calls: {};
} | {
  query_total_calls_previous: {};
};
export type MigrateMsg = "v2_0_0";
export type Addr = string;
export type ArrayOfQueryCountersResponse = QueryCountersResponse[];
export interface QueryCountersResponse {
  counter_value: Uint128;
  owner: Addr;
}